
version: '3'

services:
  # 改镜像会暴露出自身的 `header` 信息
  whoami:
    image: containous/whoami
    networks:
      - my-app
    labels:
      # 设置Host 为 whoami.docker.localhost 进行域名访问
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.dreamer2q.wang`)"

# 使用已存在的 traefik 的 network
networks:
  default:
    external:
      name: my-app

